dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.6'

# To install packages which are not on pip
#before_install:
#  - sudo apt-get install ...
#addons:
#  apt:
#    update: true

# command to install dependencies
install:
  - pip install -r requirements/default.txt
  - pip install -r requirements/tests.txt

# commands to run tests 
script:
  - black --check . --exclude docs/
  - coverage run -m pytest

after_success:
  - coverage report -m
  - coveralls

#env:
#  - EXECUTE_TESTS_ON=skip

jobs:
  include:
    - if: branch IN (master)
      env: COVERALLS_REPO_TOKEN=${{ secrets.coverage_token }} EXECUTE_TESTS_ON=master
    - if: branch IN (dev)
      env: COVERALLS_REPO_TOKEN=${{ secrets.coverage_token }} EXECUTE_TESTS_ON=dev
    - if: branch NOT IN (master, dev)
      env: EXECUTE_TESTS_ON=skip
#jobs:
#  include:
#    - stage: "Tests"                # naming the Tests stage
#      name: "Linting Tests"            # names the first Tests stage job
#      script: flake8
#      script: pylint
# for later stages
#    - script: ./integration-tests
#      name: "Integration Tests"     # names the second Tests stage job
#    - stage: deploy
#      name: "Deploy to GCP"
#      script: ./deploy

# blocklist
#branches:
#  except:
#  - branch_name1
#  - branch_name2

# safelist
#branches:
#  only:
#  - branch_name1
#  - branch_name2
